import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col h-screen w-screen`}>
        <div className="h-full flex flex-col p-6 text-center">
          <p className="mb-6 leading-7 [&:not(:first-child)]:mt-6">
            Root Layout
          </p>
          <div className="flex-1 border rounded-lg h-full">{children}</div>
        </div>
      </body>
    </html>
  );
}
