import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavLink } from "@/components/navlink";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex`}
      >
        <aside className="w-52 border-r p-4">
          <nav>
            <ul className="space-y-1">
              <li>
                <NavLink href="/static">Static Page</NavLink>
              </li>
              <li>
                <NavLink href="/dynamic">Dynamic Page</NavLink>
              </li>
            </ul>
          </nav>
        </aside>
        <main className="h-screen flex-1 flex justify-center items-center">
        {children}
        </main>
      </body>
    </html>
  );
}
